kdt-proj1-team/groupware

src/main/java/com/example/projectdemo/domain/attend/controller/AttendController.java
src/main/java/com/example/projectdemo/domain/attend/dao/AttendDAO.java
src/main/java/com/example/projectdemo/domain/attend/dto/AttendDTO.java
src/main/java/com/example/projectdemo/domain/attend/service/AttendService.java
src/main/java/com/example/projectdemo/domain/notification/crawler/NoticeCrawler.java
src/main/java/com/example/projectdemo/domain/web/controller/WebController.java
src/main/resources/static/css/attendAnnualStatistics.css
src/main/resources/static/css/attendLeavesHistory.css
src/main/resources/static/css/attendMain.css
src/main/resources/static/css/attendWorkDetails.css
src/main/resources/static/css/attendWorkSchedule.css
src/main/resources/templates/attend/attendAnnualStatistics.html
src/main/resources/templates/attend/attendLeavesHistory.html
src/main/resources/templates/attend/attendMain.html
src/main/resources/templates/attend/attendWorkDetails.html
src/main/resources/templates/attend/attendWorkSchedule.html
src/main/resources/templates/intro.html

근태관리 추가했습니다! 

---

src/main/java/com/example/projectdemo/domain/web/controller/WebController.java
src/main/resources/templates/auth/login.html
src/main/resources/templates/intro.html
src/main/resources/templates/main.html

Add after login main page main.html

---

src/main/java/com/example/projectdemo/domain/edsm/controller/EdsmController.java
src/main/java/com/example/projectdemo/domain/edsm/dao/EdsmDAO.java
src/main/java/com/example/projectdemo/domain/edsm/dto/EdsmDTO.java
src/main/java/com/example/projectdemo/domain/edsm/services/EdsmService.java
src/main/resources/static/assets/css/edsm/edsm.css
src/main/resources/static/assets/css/edsm/edsmInput.css
src/main/resources/templates/edsm/edsmComplete.html
src/main/resources/templates/edsm/edsmInput.html
src/main/resources/templates/edsm/edsmMain.html
src/main/resources/templates/edsm/edsmProgress.html
src/main/resources/templates/intro.html

전자결재 시스템 추가 사항입니다

---

src/main/java/com/example/projectdemo/domain/attend/controller/AttendController.java
src/main/resources/templates/attend/attendMain.html

컨트롤러 변수명 수정했습니다!

---

src/main/java/com/example/projectdemo/domain/attend/controller/AttendController.java
src/main/java/com/example/projectdemo/domain/attend/dto/AttendDTO.java
src/main/resources/mappers/AttendMapper.xml
src/main/resources/static/assets/css/attend/attendAnnualStatistics.css
src/main/resources/templates/attend/attendAnnualStatistics.html
src/main/resources/templates/attend/attendMain.html

근무계획이랑 보정평균근무는 종훈이형님이랑 전자결제하고 해야돼서 아직 안되어있고 나머지는 다 작동됩니다!

연간통계 수정완료입니다!

---

src/main/java/com/example/projectdemo/domain/edsm/controller/EdsmController.java
src/main/java/com/example/projectdemo/domain/edsm/dao/EdsmDAO.java
src/main/java/com/example/projectdemo/domain/edsm/dto/EdsmBcDTO.java
src/main/java/com/example/projectdemo/domain/edsm/dto/EdsmDTO.java
src/main/java/com/example/projectdemo/domain/edsm/enums/EdsmStatus.java
src/main/resources/mappers/EdsmMapper.xml
src/main/resources/static/assets/css/edsm/edsmInput.css
src/main/resources/templates/edsm/edsmInputBc.html
src/main/resources/templates/edsm/edsmInputCdv.html

edms DB에 데이터 추가 작업

---

src/main/java/com/example/projectdemo/domain/leave/controller/LeaveController.java
src/main/java/com/example/projectdemo/domain/leave/dao/LeavesDAO.java
src/main/java/com/example/projectdemo/domain/leave/dto/LeavesDTO.java
src/main/java/com/example/projectdemo/domain/leave/service/LeavesService.java
src/main/resources/static/assets/css/leave/leavesForm.css
src/main/resources/templates/attend/attendAnnualStatistics.html
src/main/resources/templates/attend/attendLeavesHistory.html
src/main/resources/templates/attend/attendMain.html
src/main/resources/templates/attend/attendWorkDetails.html
src/main/resources/templates/attend/attendWorkSchedule.html
src/main/resources/templates/leave/leavesForm.html

휴가 신청 폴더 생성했습니다.

---

src/main/java/com/example/projectdemo/domain/edsm/controller/EdsmController.java
src/main/resources/templates/edsm/edsmInputBc.html

edsm 결재라인 수정입니다.

---

src/main/java/com/example/projectdemo/domain/board/controller/BoardController.java
src/main/resources/static/assets/css/fragments/sidebar-common.css
src/main/resources/static/assets/css/main-page.css
src/main/resources/templates/board/list.html
src/main/resources/templates/fragments/sidebar/board-sidebar.html

board 게시판 페이지 사이드바 만들었습니다.

---

src/main/java/com/example/projectdemo/domain/edsm/controller/EdsmController.java
src/main/java/com/example/projectdemo/domain/edsm/dao/EdsmDAO.java
src/main/java/com/example/projectdemo/domain/edsm/dto/ApprovalLineDTO.java
src/main/resources/mappers/EdsmMapper.xml
src/main/resources/templates/edsm/edsmInputBc.html

전자결재 결재라인 기능 DB데이터에 저장기능 추가입니다.

edsm 결재라인 기능 추가

---

src/main/java/com/example/projectdemo/domain/leave/controller/LeaveController.java
src/main/java/com/example/projectdemo/domain/leave/dao/LeavesDAO.java
src/main/java/com/example/projectdemo/domain/leave/dto/LeavesDTO.java
src/main/java/com/example/projectdemo/domain/leave/service/LeavesService.java
src/main/resources/mappers/LeavesMapper.xml
src/main/resources/static/assets/css/attend/attendWorkSchedule.css
src/main/resources/static/assets/js/attend/attendWorkSchedule.js
src/main/resources/templates/attend/attendWorkSchedule.html
src/main/resources/templates/leave/leavesForm.html

fullcalender.js 써서 달력 구현했고 휴가신청서 기안하면 전자문서 테이블에 저장됩니다!

휴가 신청 및 근무현황 달력페이지 구현입니다

---

src/main/java/com/example/projectdemo/domain/edsm/controller/EdsmController.java
src/main/java/com/example/projectdemo/domain/edsm/dao/EdsmDAO.java
src/main/java/com/example/projectdemo/domain/edsm/dto/ApprovalLineDTO.java
src/main/java/com/example/projectdemo/domain/edsm/dto/EdsmBcDTO.java
src/main/java/com/example/projectdemo/domain/edsm/enums/ApprovalStatus.java
src/main/resources/mappers/EdsmMapper.xml
src/main/resources/templates/edsm/edsmMain.html

edsm 결재라인 수정사항

---

src/main/java/com/example/projectdemo/domain/chat/controller/ChatStompController.java
src/main/java/com/example/projectdemo/domain/chat/controller/MembershipController.java
src/main/java/com/example/projectdemo/domain/chat/dao/MembershipDAO.java
src/main/java/com/example/projectdemo/domain/chat/dto/ChatUserDTO.java
src/main/java/com/example/projectdemo/domain/chat/dto/MemberShipDTO.java
src/main/java/com/example/projectdemo/domain/chat/service/MembershipService.java
src/main/resources/mappers/MembershipMapper.xml

채팅멤버 출력 / 채팅방 삭제 기능 구현하고 예외처리 중입니다

feature/create/chat-memberlist & deleteroom

---

src/main/java/com/example/projectdemo/domain/attend/controller/AttendController.java
src/main/java/com/example/projectdemo/domain/leave/controller/LeaveController.java
src/main/java/com/example/projectdemo/domain/leave/dao/LeavesDAO.java
src/main/java/com/example/projectdemo/domain/leave/dto/LeavesDTO.java
src/main/java/com/example/projectdemo/domain/leave/service/LeavesService.java
src/main/resources/mappers/LeavesMapper.xml
src/main/resources/templates/attend/attendAnnualStatistics.html
src/main/resources/templates/attend/attendLeavesHistory.html
src/main/resources/templates/attend/attendWorkDetails.html
src/main/resources/templates/attend/attendWorkSchedule.html
src/main/resources/templates/leave/leavesForm.html

근태관리 전체 수정본입니다

---

src/main/java/com/example/projectdemo/domain/attend/controller/AttendController.java
src/main/java/com/example/projectdemo/domain/leave/controller/LeaveController.java
src/main/java/com/example/projectdemo/domain/leave/dao/LeavesDAO.java
src/main/java/com/example/projectdemo/domain/leave/dto/LeavesDTO.java
src/main/java/com/example/projectdemo/domain/leave/scheduler/LeaveScheduler.java
src/main/java/com/example/projectdemo/domain/leave/service/LeavesService.java
src/main/java/com/example/projectdemo/domain/web/controller/WebController.java
src/main/resources/mappers/LeavesMapper.xml
src/main/resources/templates/attend/attendLeavesHistory.html
src/main/resources/templates/leave/leavesForm.html
src/main/resources/templates/main.html

휴가 생성내역이랑 메인에 출 퇴근 시간 출력했습니다

---

src/main/java/com/example/projectdemo/domain/board/controller/BoardController.java
src/main/java/com/example/projectdemo/domain/board/dto/PostsDTO.java
src/main/java/com/example/projectdemo/domain/board/mapper/PostsMapper.java
src/main/java/com/example/projectdemo/domain/board/service/PostsService.java
src/main/java/com/example/projectdemo/domain/web/controller/WebController.java
src/main/resources/mappers/PostsMapper.xml
src/main/resources/templates/board/list.html
src/main/resources/templates/board/view.html

Remove. 웹 컨트롤러에서 board mapping 삭제 
Feat. 게시글 목록 조회, 게시글 상세 조회

Feat. 게시글 목록 조회, 게시글 상세 조회, Remove. 웹 컨트롤러에서 board mapping 삭제 

---

src/main/java/com/example/projectdemo/domain/attend/controller/AttendController.java
src/main/java/com/example/projectdemo/domain/attend/dao/AttendDAO.java
src/main/java/com/example/projectdemo/domain/leave/controller/LeaveController.java
src/main/resources/mappers/AttendMapper.xml
src/main/resources/static/assets/css/attend/attendWorkSchedule.css
src/main/resources/static/assets/js/attend/attendWorkSchedule.js
src/main/resources/templates/attend/attendLeavesHistory.html
src/main/resources/templates/attend/attendWorkSchedule.html

휴가 생성 내역 마무리 지었고, FullCalender쓴 부분에 근태 기록 (지각,조퇴,결근,퇴근,출근) 출력했습니다.

휴가 생성 내역과 근무 현황입니다.

---

src/main/resources/static/assets/css/attend/attendWorkSchedule.css

캘린더 디자인 수정입니다

---

src/main/java/com/example/projectdemo/config/CORSConfig.java
src/main/java/com/example/projectdemo/config/WebSocketConfig.java
src/main/java/com/example/projectdemo/domain/auth/jwt/JwtAuthenticationFilter.java
src/main/java/com/example/projectdemo/domain/chat/controller/ChatRoomController.java
src/main/java/com/example/projectdemo/domain/chat/dao/ChatRoomDAO.java
src/main/java/com/example/projectdemo/domain/chat/service/ChatRoomService.java
src/main/java/com/example/projectdemo/domain/chat/service/MembershipService.java
src/main/resources/mappers/ChatRoomMapper.xml
src/main/resources/templates/fragments/header.html

채팅방 나가기 구독 부분 추가하고 최근 메시지 내용 시간 랜더링 구현 완료했습니다.

fix/chat-delete & chat-add

---

src/main/java/com/example/projectdemo/domain/edsm/controller/EdsmController.java
src/main/java/com/example/projectdemo/domain/edsm/controller/EdsmDetailController.java
src/main/java/com/example/projectdemo/domain/edsm/controller/EdsmFormController.java
src/main/java/com/example/projectdemo/domain/edsm/dao/EdsmDAO.java
src/main/resources/mappers/EdsmMapper.xml
src/main/resources/templates/edsm/complete.html
src/main/resources/templates/edsm/edsmDetail/businessContactDetail.html
src/main/resources/templates/edsm/edsmDetail/cashDisbuVoucherDetail.html
src/main/resources/templates/edsm/edsmDetail/letterOfApprovalDetail.html
src/main/resources/templates/edsm/edsmForm/businessContact.html
src/main/resources/templates/edsm/edsmForm/cashDisbuVoucher.html
src/main/resources/templates/edsm/edsmForm/letterOfApproval.html
src/main/resources/templates/edsm/expected.html
src/main/resources/templates/edsm/input.html
src/main/resources/templates/edsm/progress.html

전자결재 detail 페이지 추가

---

src/main/java/com/example/projectdemo/domain/attend/controller/AttendController.java
src/main/java/com/example/projectdemo/domain/leave/controller/LeaveController.java
src/main/java/com/example/projectdemo/domain/work/controller/WorkController.java
src/main/java/com/example/projectdemo/domain/work/dao/WorkDAO.java
src/main/java/com/example/projectdemo/domain/work/dto/OverTimeDTO.java
src/main/java/com/example/projectdemo/domain/work/service/WorkService.java
src/main/resources/mappers/LeavesMapper.xml
src/main/resources/mappers/WorksMapper.xml
src/main/resources/static/assets/css/attend/attendAnnualStatistics.css
src/main/resources/static/assets/css/attend/attendLeavesHistory.css
src/main/resources/static/assets/css/attend/attendMain.css
src/main/resources/static/assets/css/work/overTimeForm.css
src/main/resources/static/assets/css/work/workDetails.css
src/main/resources/static/assets/css/work/workSchedule.css
src/main/resources/static/assets/js/work/workSchedule.js
src/main/resources/templates/attend/attendAnnualStatistics.html
src/main/resources/templates/attend/attendLeavesHistory.html
src/main/resources/templates/attend/attendMain.html
src/main/resources/templates/work/overTimeForm.html
src/main/resources/templates/work/workDetails.html
src/main/resources/templates/work/workSchedule.html

연장근무신청하면 전자결제테이블에 월별 내역 페이지 추가했습니다 work폴더 새로 만들었고 근무계획관련 내용 새로운 폴더에 옮겼습니다!

휴가신청서 전자문서와 연결 수정했고 연장근무신청서 추가했습니다

---

src/main/java/com/example/projectdemo/domain/board/controller/BoardController.java
src/main/java/com/example/projectdemo/domain/board/dto/PostsDTO.java
src/main/java/com/example/projectdemo/domain/board/mapper/BoardsMapper.java
src/main/java/com/example/projectdemo/domain/board/mapper/PostsMapper.java
src/main/java/com/example/projectdemo/domain/board/service/BoardsService.java
src/main/java/com/example/projectdemo/domain/board/service/PostsService.java
src/main/resources/mappers/BoardsMapper.xml
src/main/resources/mappers/PostsMapper.xml
src/main/resources/templates/board/board-layout.html
src/main/resources/templates/board/edit.html
src/main/resources/templates/board/integrated-list.html
src/main/resources/templates/board/list.html
src/main/resources/templates/fragments/sidebar/board-sidebar.html

Feat 통합 게시판 - 리스트 페이지 구현
Feat. 특정 게시판 게시글 목록 보기
Feat. 게시판 공통 사이드바에 통합 게시판 추가
Feat. 게시판 수정 기능 구현
Remove. 사용 되지 않은 코드 삭제

Feat. 게시판 리스트 페이지 구현, 게시판 수정 기능

---

src/main/java/com/example/projectdemo/domain/edsm/controller/EdsmController.java
src/main/java/com/example/projectdemo/domain/edsm/controller/EdsmDetailController.java
src/main/java/com/example/projectdemo/domain/edsm/controller/EdsmFormController.java
src/main/java/com/example/projectdemo/domain/edsm/dao/EdsmDAO.java
src/main/java/com/example/projectdemo/domain/edsm/dto/EdsmCashDisbuVoucherDTO.java
src/main/java/com/example/projectdemo/domain/edsm/services/EdsmDetailService.java
src/main/java/com/example/projectdemo/domain/edsm/services/EdsmFormService.java
src/main/java/com/example/projectdemo/domain/edsm/services/EdsmService.java
src/main/java/com/example/projectdemo/domain/edsm/statics/NaviStatics.java
src/main/resources/mappers/EdsmMapper.xml
src/main/resources/static/assets/css/edsm/edsmInputCdv.css
src/main/resources/static/assets/css/edsm/edsmMain.css
src/main/resources/templates/edsm/edsmForm/cashDisbuVoucher.html
src/main/resources/templates/edsm/error.html
src/main/resources/templates/edsm/expected.html
src/main/resources/templates/edsm/main.html

문서별 리스트 출력 수정
문서 상태별 리스트 출력 수정
결재 예정인 경우 리스트 출력 추가
문서 게시글 페이지네이션기능 추가

전자결재 문서 상태별 리스트 수정사항

---

src/main/java/com/example/projectdemo/domain/attend/controller/AttendController.java
src/main/java/com/example/projectdemo/domain/leave/controller/LeaveController.java
src/main/java/com/example/projectdemo/domain/leave/dao/LeavesDAO.java
src/main/java/com/example/projectdemo/domain/leave/service/LeavesService.java
src/main/resources/mappers/LeavesMapper.xml
src/main/resources/templates/leave/leavesForm.html

자료형 수정했습니다!

---

src/main/java/com/example/projectdemo/config/SidebarInterceptor.java
src/main/java/com/example/projectdemo/config/WebMvcConfig.java
src/main/java/com/example/projectdemo/domain/board/controller/BoardController.java
src/main/java/com/example/projectdemo/domain/board/mapper/PostsMapper.java
src/main/java/com/example/projectdemo/domain/board/service/PostsService.java
src/main/resources/mappers/PostsMapper.xml
src/main/resources/static/assets/js/fragments/sidebar-common.js
src/main/resources/templates/board/integrated-list.html
src/main/resources/templates/board/list.html
src/main/resources/templates/fragments/sidebar/board-sidebar.html

Feat. 게시판 사이드바 UI 및 권한 기반 게시판 숨김 처리
Fix. 사이드바 공통 스크립트 TypeError 오류 방지
Feat. 게시판 삭제 기능 추가

Feat. 게시판 사이드바 UI 및 권한 기반 게시판 숨김 처리 Fix. 사이드바 공통 스크립트 TypeError 오류 방지 Feat. 게시판 삭제 기능 추가

---

src/main/java/com/example/projectdemo/config/HmailserverPasswordEncoder.java
src/main/java/com/example/projectdemo/domain/employees/service/EmployeesService.java
src/main/java/com/example/projectdemo/domain/mail/dto/MailAccountDTO.java
src/main/java/com/example/projectdemo/domain/mail/mapper/MailMapper.java
src/main/java/com/example/projectdemo/domain/mail/service/MailService.java
src/main/resources/mappers/MailMapper.xml

- 그룹웨어 가입 시 메일서버 계정을 자동으로 생성
- 가입 시 기본 IMAP 폴더(INBOX 등)를 함께 생성
- 사용자 비밀번호 변경 시 메일서버 비밀번호도 함께 변경되도록 연동
- 메일서버 암호화 방식 대응을 위한 `HmailserverPasswordEncoder` 클래스 구현

메일 계정 자동 생성 및 비밀번호 동기화를 위한 기능 추가

---

src/main/java/com/example/projectdemo/domain/board/controller/BoardController.java
src/main/java/com/example/projectdemo/domain/board/controller/PostApiController.java
src/main/java/com/example/projectdemo/domain/board/service/PostsService.java
src/main/resources/templates/board/view.html

Fix. 게시글 작성자만 게시글 삭제 가능하게 수정
Fix. 존재하지 않는 뷰 'board/access-denied'로 인한 MVC 경고 수정

Fix. 게시글 작성자만 게시글 삭제 가능하게 수정 / Fix. 존재하지 않는 뷰 'board/access-denied'로 인한 MVC 경고 수정

---

src/main/java/com/example/projectdemo/domain/auth/controller/AuthController.java
src/main/java/com/example/projectdemo/domain/auth/dto/JwtResponseDTO.java

- JwtResponseDTO에 internalEmail 필드 추가
- AuthController에서 로그인 응답 시 사내 메일 주소 포함하도록 수정

Feat: JWT 응답에 사내 메일 필드 추가

---

src/main/java/com/example/projectdemo/domain/attend/controller/AttendController.java
src/main/java/com/example/projectdemo/domain/leave/controller/LeaveController.java
src/main/java/com/example/projectdemo/domain/leave/dao/LeavesDAO.java
src/main/java/com/example/projectdemo/domain/leave/service/LeavesService.java
src/main/java/com/example/projectdemo/domain/work/controller/WorkController.java
src/main/java/com/example/projectdemo/domain/work/dao/WorkDAO.java
src/main/java/com/example/projectdemo/domain/work/service/WorkService.java
src/main/resources/mappers/LeavesMapper.xml
src/main/resources/mappers/WorksMapper.xml
src/main/resources/static/assets/css/work/workSchedule.css
src/main/resources/static/assets/js/work/workSchedule.js
src/main/resources/templates/attend/attendAnnualStatistics.html
src/main/resources/templates/attend/attendLeavesHistory.html
src/main/resources/templates/work/workSchedule.html

캘린더에 휴가와 근무 계획 출력했고 연간 통계 페이지 근무 계획, 보정 평균 근무 수정해서 마무리 했습니다!

근무 계획 캘린더랑 연간 통계 페이지 수정했습니다.

---

src/main/java/com/example/projectdemo/domain/mail/controller/MailController.java
src/main/resources/templates/auth/login.html
src/main/resources/templates/mail/mail.html

- 그룹웨어 로그인 시 메일 계정 정보로 Roundcube 세션 자동 생성
- 웹메일 페이지 접근 시 별도 로그인 없이 바로 접속 가능하도록 구현

Feat: 그룹웨어 로그인 시 메일(Roundcube) 자동 로그인 연동

---

src/main/java/com/example/projectdemo/domain/edsm/controller/EdsmController.java
src/main/java/com/example/projectdemo/domain/edsm/controller/EdsmDetailController.java
src/main/java/com/example/projectdemo/domain/edsm/controller/EdsmFilesController.java
src/main/java/com/example/projectdemo/domain/edsm/controller/EdsmFormController.java
src/main/java/com/example/projectdemo/domain/edsm/dao/EdsmFilesDAO.java
src/main/java/com/example/projectdemo/domain/edsm/dto/EdsmFilesDTO.java
src/main/java/com/example/projectdemo/domain/edsm/services/EdsmDetailService.java
src/main/java/com/example/projectdemo/domain/edsm/services/EdsmFilesService.java
src/main/java/com/example/projectdemo/domain/edsm/services/EdsmFormService.java
src/main/resources/mappers/EdsmMapper.xml
src/main/resources/static/assets/css/edsm/edsmBusinessDetail.css
src/main/resources/static/assets/css/edsm/edsmCashDisbuVoucherDetail.css
src/main/resources/static/assets/css/edsm/edsmLetterOfApprovalDetail.css
src/main/resources/templates/edsm/edsmDetail/businessContactDetail.html
src/main/resources/templates/edsm/edsmDetail/cashDisbuVoucherDetail.html
src/main/resources/templates/edsm/edsmDetail/letterOfApprovalDetail.html
src/main/resources/templates/edsm/edsmForm/businessContact.html
src/main/resources/templates/edsm/edsmForm/letterOfApproval.html
src/main/resources/templates/edsm/input.html
src/main/resources/templates/edsm/main.html

전자결재 기안시 파일 첨부 기능 추가
기안문서 Detail 페이지에서 첨부된 파일 확인 및 다운로드 기능 추가

전자결재 첨부파일 변경사항

---

src/main/java/com/example/projectdemo/config/WebConfig.java
src/main/java/com/example/projectdemo/domain/board/controller/PostApiController.java
src/main/resources/templates/board/write.html

Feat. 게시판 Summernote 이미지 등록 기능 추가

Feat. 게시판 Summernote 이미지 등록 기능 추가

---

src/main/java/com/example/projectdemo/domain/contact/controller/ContactApiController.java
src/main/java/com/example/projectdemo/domain/contact/mapper/ContactMapper.java
src/main/java/com/example/projectdemo/domain/contact/service/ContactService.java
src/main/resources/mappers/ContactsMapper.xml
src/main/resources/static/assets/css/contact/contact.css
src/main/resources/static/assets/js/contact/contact.js
src/main/resources/templates/contact/contact.html

- 사용자가 개인 주소록에서 연락처를 선택하여 삭제할 수 있는 기능 구현
- 삭제 요청은 ID 기반으로 처리되며, DB에서 해당 연락처 데이터를 제거함

Feat: 개인 주소록 연락처 삭제 기능 추가

---

src/main/java/com/example/projectdemo/domain/edsm/controller/EdsmDetailController.java
src/main/java/com/example/projectdemo/domain/leave/controller/LeaveController.java
src/main/java/com/example/projectdemo/domain/leave/dao/LeavesDAO.java
src/main/java/com/example/projectdemo/domain/leave/service/LeavesService.java
src/main/java/com/example/projectdemo/domain/work/dao/WorkDAO.java
src/main/java/com/example/projectdemo/domain/work/service/WorkService.java
src/main/resources/mappers/LeavesMapper.xml
src/main/resources/mappers/WorksMapper.xml
src/main/resources/static/assets/css/edsm/edsmLeavesDetail.css
src/main/resources/static/assets/css/edsm/edsmOvertimeDetail.css
src/main/resources/static/assets/css/leave/leavesForm.css
src/main/resources/templates/edsm/edsmDetail/leavesDetail.html
src/main/resources/templates/edsm/edsmDetail/overtimeDetail.html
src/main/resources/templates/leave/leavesForm.html

휴가신청서, 연장근무신청서 detail만들었고 전자결재리스트에 출력했습니다! 첨부파일도 DB에 넣는 것 까지 했고 다운로드는 아직 입니다!

전자결재와 휴가신청서, 연장근무신청서 디테일 및 첨부파일 수정

---

src/main/resources/static/assets/css/contact/contact.css
src/main/resources/static/assets/js/contact/contact.js
src/main/resources/templates/contact/contact.html

- 공유 주소록에서는 이름, 이메일, 전화, 부서명, 직급 정보를 표시
- 개인 주소록에서는 이름, 이메일, 전화, 메모 정보를 표시하며 행 클릭 시 모달 창으로 노출

Feat: 연락처 상세 정보 모달 기능 추가

---

src/main/java/com/example/projectdemo/domain/work/controller/WorkController.java
src/main/java/com/example/projectdemo/domain/work/service/WorkService.java
src/main/resources/mappers/WorksMapper.xml
src/main/resources/static/assets/css/attend/attendAnnualStatistics.css
src/main/resources/static/assets/css/attend/attendLeavesHistory.css
src/main/resources/static/assets/css/attend/attendMain.css
src/main/resources/static/assets/css/leave/leavesForm.css
src/main/resources/static/assets/css/work/overTimeForm.css
src/main/resources/static/assets/css/work/workDetails.css
src/main/resources/static/assets/css/work/workSchedule.css
src/main/resources/templates/attend/attendAnnualStatistics.html
src/main/resources/templates/attend/attendLeavesHistory.html
src/main/resources/templates/attend/attendMain.html
src/main/resources/templates/edsm/edsmDetail/leavesDetail.html
src/main/resources/templates/edsm/edsmDetail/overtimeDetail.html
src/main/resources/templates/fragments/header.html
src/main/resources/templates/leave/leavesForm.html
src/main/resources/templates/work/overTimeForm.html
src/main/resources/templates/work/workDetails.html
src/main/resources/templates/work/workSchedule.html

연장근무신청내역 작동되게 수정했고 연장근무신청서도 작동잘 됩니다! 그리고 제가 구현한 페이지 전체에 전환되는 거 확인해서 다 수정했고 사이드바와 헤더 추가해서 전체페이지에 추가했습니다

테스트 오류 수정 내역

---

src/main/resources/templates/edsm/edsmDetail/leavesDetail.html
src/main/resources/templates/edsm/edsmDetail/overtimeDetail.html

작성자가 로그인한 사람으로 나오길 래 진짜 작성자로 출력했습니다!

신청서 detail에 작성자 출력 수정

---

src/main/java/com/example/projectdemo/domain/board/controller/AttachmentsApiController.java
src/main/java/com/example/projectdemo/domain/board/controller/BoardController.java
src/main/java/com/example/projectdemo/domain/board/controller/PostApiController.java
src/main/java/com/example/projectdemo/domain/board/mapper/AttachmentsMapper.java
src/main/java/com/example/projectdemo/domain/board/service/AttachmentsService.java
src/main/java/com/example/projectdemo/domain/board/service/PostsService.java
src/main/resources/mappers/AttachmentsMapper.xml
src/main/resources/templates/board/view.html
src/main/resources/templates/board/write.html

Feat. 게시판 파일첨부 기능 추가

---

src/main/java/com/example/projectdemo/domain/auth/controller/AuthController.java
src/main/java/com/example/projectdemo/domain/leave/controller/LeaveController.java
src/main/java/com/example/projectdemo/domain/leave/dao/LeavesDAO.java
src/main/java/com/example/projectdemo/domain/leave/dto/LeaveGrantsDTO.java
src/main/java/com/example/projectdemo/domain/leave/service/LeavesService.java
src/main/resources/mappers/LeavesMapper.xml
src/main/resources/static/assets/css/attend/attendLeavesHistory.css
src/main/resources/static/assets/css/leave/leavesForm.css
src/main/resources/static/assets/css/work/overTimeForm.css
src/main/resources/static/assets/css/work/workDetails.css
src/main/resources/static/assets/css/work/workSchedule.css
src/main/resources/static/assets/js/work/workSchedule.js
src/main/resources/templates/attend/attendLeavesHistory.html
src/main/resources/templates/attend/attendMain.html
src/main/resources/templates/leave/leavesForm.html
src/main/resources/templates/work/overTimeForm.html
src/main/resources/templates/work/workSchedule.html

페이지 사이드바 및 헤더 통일했고 신청서에서 나올 수 있는 예외들 alert처리 했고 신입이 아닌 직원 기준 휴가 생성 로직 구현했습니다 FullCalendar에 googleCalendar Api써서 공휴일 반영했습니다!

근태관리페이지 전체 디자인 통일, 신청서 예외 alert처리, 휴가생성로직, 캘린더 수정

---

src/main/java/com/example/projectdemo/domain/auth/controller/AuthController.java
src/main/java/com/example/projectdemo/domain/leave/dao/LeavesDAO.java
src/main/java/com/example/projectdemo/domain/leave/service/LeavesService.java
src/main/resources/mappers/LeavesMapper.xml
src/main/resources/templates/work/overTimeForm.html

직원 가입할때 입사일기준으로 휴가 계산해서 employees테이블에 휴가생성된 채로 가입되는거 확인했습니다!!!

휴가생성로직 수정입니다.

---

src/main/java/com/example/projectdemo/domain/leave/dao/LeavesDAO.java

메퍼쿼리문 id랑 dao에서 쓴 이름이 달라서 회원가입할때 오류나서 수정했습니다 테스트해보니까 오류없이 잘 작동합니다!

회원가입 휴가생성 오류 수정입니다

---

src/main/java/com/example/projectdemo/domain/leave/controller/LeaveController.java
src/main/java/com/example/projectdemo/domain/leave/dto/LeavesDTO.java
src/main/java/com/example/projectdemo/domain/web/controller/WebController.java
src/main/resources/static/assets/css/work/workDetails.css
src/main/resources/static/assets/css/work/workSchedule.css
src/main/resources/templates/attend/attendLeavesHistory.html
src/main/resources/templates/attend/attendMain.html
src/main/resources/templates/leave/leavesForm.html
src/main/resources/templates/main.html

webcontroller에서 보내고 있던 시간나타내는 부분 삭제했고 뷰에서만 시간 랜더링해서 흘러가게 수정했습니다!

근태관리 페이지 출력 확인 및 수정 main.html에 시간 수정

---

src/main/java/com/example/projectdemo/domain/work/controller/WorkController.java
src/main/resources/static/assets/css/main-page.css
src/main/resources/templates/main.html
src/main/resources/templates/work/overTimeForm.html

Fullcalendar API 써서 구현했고 googleCalendar로 공휴일 추가했습니다!

main페이지 캘린더 수정

---

src/main/resources/static/assets/css/contact/contact.css
src/main/resources/static/assets/js/contact/contact.js

- 검색 상태에서 연락처 추가 시 리스트에 즉시 반영되도록 처리
- 검색 상태에서 연락처 수정 시 결과 리스트가 자동 갱신되도록 처리
- 검색 상태에서 연락처 삭제 시 리스트와 체크박스 상태가 자동 갱신되도록 처리
- 삭제 후 전체 선택 해제, 선택 개수 기준 삭제 버튼 상태 처리 포함
- 공유 및 개인 주소록에서 이메일 클릭 시 메일 작성 팝업 창 열리도록 구현
- 검색 조건이 유지된 상태에서도 주소록의 CRUD 동작 결과가 실시간으로 반영되도록 하여 사용자 경험 개선
- 수동 새로고침 없이도 UI가 자연스럽게 업데이트되도록 처리
- 이메일 클릭 시 편리하게 메일을 작성할 수 있도록 기능성 향상
1. 검색 상태에서 연락처를 추가/수정/삭제한 후 리스트가 자동으로 갱신되는지 확인
2. 체크박스 선택/해제 시 전체 선택 상태 및 삭제 버튼 상태가 올바르게 동작하는지 확인
3. 이메일 클릭 시 새 창으로 메일 작성 페이지가 정상적으로 열리는지 확인

주소록 검색 상태 연동 개선 및 이메일 작성 팝업 기능 추가

---

src/main/java/com/example/projectdemo/domain/board/controller/BoardApiController.java
src/main/java/com/example/projectdemo/domain/board/controller/BoardController.java
src/main/java/com/example/projectdemo/domain/board/dto/BoardPermissionsDTO.java
src/main/java/com/example/projectdemo/domain/board/dto/BoardsDTO.java
src/main/java/com/example/projectdemo/domain/board/mapper/BoardPermissionsMapper.java
src/main/java/com/example/projectdemo/domain/board/mapper/BoardsMapper.java
src/main/java/com/example/projectdemo/domain/board/service/BoardsService.java
src/main/java/com/example/projectdemo/domain/employees/controller/EmployeesApiController.java
src/main/java/com/example/projectdemo/domain/employees/mapper/EmployeesMapper.java
src/main/java/com/example/projectdemo/domain/employees/service/EmployeesService.java
src/main/resources/mappers/BoardPermissionsMapper.xml
src/main/resources/mappers/BoardsMapper.xml
src/main/resources/mappers/EmployeesMapper.xml
src/main/resources/static/assets/js/fragments/sidebar-common.js
src/main/resources/templates/board/board-layout.html
src/main/resources/templates/board/create.html
src/main/resources/templates/fragments/sidebar/board-sidebar.html

Feat. 게시판 모듈 권한 시스템 간소화 및 사용자 정보 표시 개선
Feat. 게시판 만들기 페이지 기능 구현
Fix. sidebar 요소가 없을 경우 예외 발생 방지를 위해 null 체크 추가

Feat. 게시판 생성 기능 구현 및 권한/사이드바 로직 개선

---

src/main/resources/static/assets/js/contact/contact.js
src/main/resources/static/assets/js/mypage/mypage.js
src/main/resources/templates/contact/contact.html

- 마이페이지 입력값 유효성 검사 정규식 수정
- 주소록 입력 필드에 길이 제한 추가
- 주소록 입력 시 전화번호 및 이메일 유효성 검사 기능 추가

마이페이지 및 주소록 입력값 유효성 검증 기능 추가 및 개선

---

src/main/java/com/example/projectdemo/domain/attendance/mapper/AttendanceMapper.java
src/main/java/com/example/projectdemo/domain/attendance/scheduler/AutoCheckoutScheduler.java
src/main/java/com/example/projectdemo/domain/attendance/service/AttendanceService.java
src/main/java/com/example/projectdemo/domain/employees/mapper/EmployeesMapper.java
src/main/resources/mappers/AttendanceMapper.xml
src/main/resources/mappers/EmployeesMapper.xml
src/main/resources/static/assets/js/work/workSchedule.js
src/main/resources/templates/attend/attendMain.html
src/main/resources/templates/main.html

캘린더에 공휴일이벤트를 누르면 googleCalendar 로 창이 넘어가는 문제가 있어서 수정했고 근태 기록 DB에 저장하는 부분에서 status 업데이트 하는 로직을 attendance테이블 각각의 row로 저장하는 로직으로 수정했고 스케쥴러에서 18시05분에 출근 시간이 없는 직원들의 status를 결근 처리되게 했습니다!! 테스트는 아직입니다!

캘린더 수정 및 근태 기록 수정

---

src/main/java/com/example/projectdemo/config/HolidayApiProperties.java
src/main/java/com/example/projectdemo/domain/attendance/service/HolidayService.java

하드코딩 수정입니다!

---

src/main/resources/static/assets/css/edsm/edsmMain.css
src/main/resources/templates/edsm/edsmMyDocument/approvalDocument.html
src/main/resources/templates/edsm/edsmMyDocument/myWrittenDocument.html
src/main/resources/templates/edsm/edsmMyDocument/rejectedDocument.html
src/main/resources/templates/edsm/expected.html
src/main/resources/templates/edsm/main.html
src/main/resources/templates/edsm/wait.html

반응형 스타일 구현
작아졌을시 사이드바가 사라지고 select > option으로 선택해서 이동할수있음.

전자결재 반응형 변경사항

---

src/main/resources/templates/work/overTimeForm.html

연장근무신청서 수정

---

src/main/java/com/example/projectdemo/config/AuthorizationInterceptor.java
src/main/java/com/example/projectdemo/domain/board/controller/BoardController.java
src/main/java/com/example/projectdemo/domain/board/dto/BoardsDTO.java
src/main/java/com/example/projectdemo/domain/board/mapper/PostsMapper.java
src/main/java/com/example/projectdemo/domain/board/service/PostsService.java
src/main/resources/mappers/BoardsMapper.xml
src/main/resources/mappers/PostsMapper.xml
src/main/resources/templates/board/board-layout.html
src/main/resources/templates/board/manage.html

Feat. 관리자 권한이 없는 경우 /board/manage 접근 제한 추가
Feat. 게시판 관리 페이지 구현 및 게시판별 게시글 수 정보 추가

Feat. 게시판 관리 페이지 구현 및 게시글 수 표시, 관리자 아닐 경우 접근 제한 추가

---

src/main/resources/templates/edsm/edsmForm/businessContact.html
src/main/resources/templates/edsm/edsmForm/cashDisbuVoucher.html
src/main/resources/templates/edsm/edsmForm/letterOfApproval.html

전자결재 기안문 입력 폼 변경사항

---

src/main/java/com/example/projectdemo/domain/board/controller/BoardApiController.java
src/main/java/com/example/projectdemo/domain/board/controller/BoardController.java
src/main/java/com/example/projectdemo/domain/board/mapper/BoardsMapper.java
src/main/java/com/example/projectdemo/domain/board/service/BoardsService.java
src/main/java/com/example/projectdemo/domain/org/controller/OrgApiController.java
src/main/java/com/example/projectdemo/domain/org/controller/OrgController.java
src/main/resources/mappers/BoardsMapper.xml
src/main/resources/static/assets/css/org/org.css
src/main/resources/templates/board/edit.html
src/main/resources/templates/board/manage.html
src/main/resources/templates/fragments/header.html
src/main/resources/templates/fragments/sidebar/main-sidebar.html
src/main/resources/templates/fragments/sidebar/org-sidebar.html
src/main/resources/templates/org/org.html

Feat. 게시판 삭제 기능 추가
Feat. 조직도 페이지 구현 - 부서별 사원 정보 조회 및 상세 정보 모달 기능 추가]
Fix. 게시글 수정 시 Summernote 에디터에서 HTML 태그가 텍스트로 표시되는 문제 해결
Feat. 조직도 페이지 href 연결

게시판 삭제 기능, 조직도 페이지(부서별 사원 조회 및 모달), 게시글 수정 시 에디터 태그 표시 문제 수정, 조직도 페이지 href 연결

---

src/main/java/com/example/projectdemo/domain/board/controller/PostApiController.java
src/main/java/com/example/projectdemo/domain/board/mapper/PostsMapper.java
src/main/java/com/example/projectdemo/domain/board/service/PostsService.java
src/main/java/com/example/projectdemo/domain/contact/controller/ContactApiController.java
src/main/java/com/example/projectdemo/domain/mypage/controller/MypageApiController.java
src/main/java/com/example/projectdemo/domain/mypage/controller/MypageController.java
src/main/resources/mappers/PostsMapper.xml
src/main/resources/static/assets/css/contact/contact.css
src/main/resources/static/assets/css/mypage/mypage.css
src/main/resources/static/assets/js/mypage/mypage.js
src/main/resources/templates/contact/contact.html
src/main/resources/templates/mypage/mypage.html

- 마이페이지에서 로그인한 사용자의 게시글을 조회하고 삭제할 수 있도록 기능 구현
- 게시글 목록에서 내가 작성한 게시글을 표시
- 게시글 삭제 시 confirm 확인창을 통해 삭제 처리
- 삭제 후 리스트가 자동으로 갱신되며, 게시글이 없을 경우 안내 문구 표시
- 주소록 페이지 사이드바 아이콘 변경
- 기존 아이콘을 보다 직관적인 주소록 아이콘으로 교체
1. 게시판에서 글 작성 후 마이페이지 접속 → 게시글 목록 확인
2. 게시글 삭제 → confirm 확인창 노출 및 삭제 후 목록 갱신 확인
3. 주소록 페이지 접근 시 사이드바 아이콘이 변경된 것 확인

마이페이지 게시글 조회/삭제 기능 추가 및 주소록 사이드바 아이콘 변경

---

src/main/resources/templates/fragments/header.html

헤더 dropdown 부분에 근태 관리 버튼 경로가 잘못되어 있어서 수정했습니다!

header.html 수정

---

src/main/resources/static/assets/css/fragments/sidebar-common.css
src/main/resources/templates/fragments/sidebar/board-sidebar.html

Fix. 게시판 드롭다운 메뉴 작동 오류 수정

---

src/main/resources/static/assets/css/mypage/mypage.css
src/main/resources/static/assets/js/mypage/mypage.js

- 실제 댓글 데이터를 연동하기 위한 레이아웃 구조 미리 구성

Design: 마이페이지에 나의 댓글 영역 하드코딩으로 추가

---

src/main/java/com/example/projectdemo/domain/board/controller/CommentsApiController.java
src/main/java/com/example/projectdemo/domain/board/mapper/CommentsMapper.java
src/main/java/com/example/projectdemo/domain/board/service/CommentsService.java
src/main/java/com/example/projectdemo/domain/mypage/controller/MypageApiController.java
src/main/java/com/example/projectdemo/domain/mypage/dto/MyCommentDTO.java
src/main/resources/mappers/CommentsMapper.xml
src/main/resources/static/assets/css/mypage/mypage.css
src/main/resources/static/assets/js/contact/contact.js
src/main/resources/static/assets/js/mypage/mypage.js
src/main/resources/templates/board/view.html

- 마이페이지에서 로그인한 사용자가 작성한 댓글을 확인할 수 있는 기능 추가
- 댓글 삭제 버튼 제공, 삭제 시 confirm 확인창 노출
- 삭제 후 리스트 자동 갱신 처리
- 마이페이지 선택 체크박스가 동작하지 않던 문제 수정
- 전체 선택 및 개별 선택 동작 개선
- 검색 상태에서 주소록 이메일 클릭 시 상세 모달이 뜨던 문제 수정
- 검색 중에는 상세 모달이 뜨지 않고 메일 작성 팝업만 열리도록 처리

마이페이지 댓글 관리 기능 추가 및 UI 동작 오류 수정

---

src/main/resources/templates/fragments/header.html

- 로그인 후 메인페이지에서 현재페이지 토글 제거
- 헤더에 로고 이미지 추가 및 스타일 적용
- 헤더 현재페이지 토글에 경로 연결 처리

Design: 헤더 UI 구성 수정 및 현재페이지 토글 경로 추가

---

src/main/java/com/example/projectdemo/domain/edsm/dto/EdsmCashDisbuVoucherDTO.java
src/main/resources/mappers/EdsmMapper.xml
src/main/resources/static/assets/css/edsm/edsm.css
src/main/resources/static/assets/css/edsm/edsmBusinessContact.css
src/main/resources/static/assets/css/edsm/edsmBusinessDetail.css
src/main/resources/static/assets/css/edsm/edsmCashDisbuVoucherDetail.css
src/main/resources/static/assets/css/edsm/edsmInput.css
src/main/resources/static/assets/css/edsm/edsmInputCdv.css
src/main/resources/static/assets/css/edsm/edsmLeavesDetail.css
src/main/resources/static/assets/css/edsm/edsmLetterOfApproval.css
src/main/resources/static/assets/css/edsm/edsmLetterOfApprovalDetail.css
src/main/resources/static/assets/css/edsm/edsmMain.css
src/main/resources/static/assets/css/edsm/edsmOvertimeDetail.css
src/main/resources/templates/edsm/edsmDetail/businessContactDetail.html
src/main/resources/templates/edsm/edsmDetail/cashDisbuVoucherDetail.html
src/main/resources/templates/edsm/edsmDetail/leavesDetail.html
src/main/resources/templates/edsm/edsmDetail/letterOfApprovalDetail.html
src/main/resources/templates/edsm/edsmDetail/overtimeDetail.html
src/main/resources/templates/edsm/edsmForm/letterOfApproval.html
src/main/resources/templates/edsm/edsmMyDocument/approvalDocument.html
src/main/resources/templates/edsm/edsmMyDocument/myWrittenDocument.html
src/main/resources/templates/edsm/edsmMyDocument/rejectedDocument.html
src/main/resources/templates/edsm/expected.html
src/main/resources/templates/edsm/wait.html

전자결재 대기문서 요청 오류 - 수정완료
전자결재 - 품의서/지출결의서 반려사유 안나옴 - 수정완료
전자결재 - 지출자: 사번출력 -> 수정 완료
나의 문서함 페이지 내 날짜 필터 추가
결재 선택 모달에서 반려 승인 선택시  처리가 늦어지면 처리중이라는 로딩 스피너 설정

전자결재 수정 및 변경사항

---

src/main/java/com/example/projectdemo/domain/attendance/scheduler/AutoCheckoutScheduler.java
src/main/java/com/example/projectdemo/domain/attendance/service/AutoCheckoutService.java

AutoCheckoutScheduler에 status가 조퇴인 직원들은 자동 퇴근 스킵 처리했습니다! 
AutoCheckoutService 이건 전체 주석처리했습니다!

자동 퇴근 스케쥴러 수정

---

src/main/java/com/example/projectdemo/domain/edsm/dao/EdsmDAO.java
src/main/java/com/example/projectdemo/domain/edsm/services/EdsmDetailService.java
src/main/resources/mappers/EdsmMapper.xml

휴가 신청시 바로 연차 갯수 차감 이슈로 인하여 
결재 라인 로직 트리거를 삭제로 프로시저로 변경 
프로시져 로직 재구성

전자결재 결재라인 및 연차 변경사항

---

src/main/java/com/example/projectdemo/domain/attendance/enums/AttendanceStatus.java
src/main/resources/mappers/AttendMapper.xml
src/main/resources/templates/leave/leavesForm.html

휴가신청서에 잔여휴가가 있는 데 잔여휴가가 없다고 alert가 뜨길래 수정했고 attendance테이블 status enum을 병가로 되어있는거 반차로 수정했습니다 연간통계에서 휴가일수를 정수형으로 하고 있었는데 decimal로 바꿔서 출력했습니다!

휴가신청서 수정 및 attendance테이블 status enum 수정 연간통계 타입 수정

---

src/main/java/com/example/projectdemo/domain/attendance/mapper/AttendanceMapper.java
src/main/java/com/example/projectdemo/domain/attendance/scheduler/AutoCheckoutScheduler.java
src/main/resources/mappers/AttendanceMapper.xml

이미 퇴근 기록 존재하는 직원(조퇴 기록) 자동 퇴근 처리 X
출근이나 지각 기록이 있는 직원 자동 퇴근 처리 O
출근 기록이 없는 직원 자동 결근 처리 O
공휴일 및 주말 자동 결근 처리 X
List<Attendance> getAttendanceListByEmployeeAndDate(@Param("empId") Integer empId, @Param("today") LocalDate today);
전 직원 근태 기록 조회하는 메소드 잘못되어 있길래 수정

자동 퇴근 처리 스케쥴러 최종 수정!!!!

---

src/main/java/com/example/projectdemo/domain/work/controller/WorkController.java
src/main/resources/static/assets/css/main-page.css
src/main/resources/static/assets/js/work/workSchedule.js
src/main/resources/templates/main.html

메인페이지 캘린더에 회사창립일 저희 회식날짜로 추가했고, 근무캘린더에 연차표시되는 게 시작날짜밖에 안떠서 수정했습니다!

메인페이지 및 근무캘린더 수정

---

src/main/java/com/example/projectdemo/domain/employees/service/EmployeesService.java

- EmployeesService에서 관리자에 의한 부서/직급 변경 시 Roundcube 주소록의 부서명 및 직급도 함께 갱신

Feat: 사원 부서 및 직급 변경 시 Roundcube 공유 주소록 정보도 함께 수정되도록 연동

---

src/main/java/com/example/projectdemo/domain/board/controller/BoardApiController.java
src/main/java/com/example/projectdemo/domain/board/controller/BoardController.java
src/main/java/com/example/projectdemo/domain/board/dto/BoardsDTO.java
src/main/java/com/example/projectdemo/domain/board/service/BoardsService.java
src/main/resources/static/assets/css/board/board-common.css
src/main/resources/templates/board/view.html

Fix. 게시글 상세 페이지에서 수정/삭제 버튼 표시 오류 수정
Fix. Summernote 에디터 이미지가 게시판 영역을 벗어나는 문제 해결
Feat. 게시판 일괄 삭제 기능 구현

Fix & Feat. 게시글 상세 버튼 표시 오류 수정 및 썸머노트 이미지 크기 제한, 게시판 일괄 삭제 기능 추가

---

src/main/resources/static/assets/css/mypage/mypage.css
src/main/resources/static/assets/js/mypage/mypage.js
src/main/resources/templates/mypage/mypage.html

- 버튼 클릭 시 사이드바 열고 닫히는 전체 동작 정상 작동되도록 구현

Feat: 마이페이지 사이드바 토글 반응형 기능 완성

---

src/main/java/com/example/projectdemo/domain/attend/controller/AttendController.java
src/main/java/com/example/projectdemo/domain/leave/controller/LeaveController.java
src/main/java/com/example/projectdemo/domain/work/controller/WorkController.java
src/main/resources/static/assets/css/attend/attendAnnualStatistics.css
src/main/resources/static/assets/css/attend/attendLeavesHistory.css
src/main/resources/static/assets/css/attend/attendMain.css
src/main/resources/static/assets/css/leave/leavesForm.css
src/main/resources/static/assets/css/work/overTimeForm.css
src/main/resources/static/assets/css/work/workDetails.css
src/main/resources/static/assets/css/work/workSchedule.css
src/main/resources/templates/work/workDetails.html

컨트롤러에 view로 바로 이동하는 return들은 상대경로로 수정했고 전체페이지 사이드바 전자결제랑 통일했습니다!!

컨트롤러 return 수정 및 전체 페이지 사이드바 통일

---

src/main/java/com/example/projectdemo/domain/work/controller/WorkController.java
src/main/java/com/example/projectdemo/domain/work/dto/OverTimeDTO.java
src/main/resources/static/assets/js/work/workSchedule.js
src/main/resources/templates/attend/attendAnnualStatistics.html
src/main/resources/templates/attend/attendLeavesHistory.html
src/main/resources/templates/attend/attendMain.html
src/main/resources/templates/leave/leavesForm.html
src/main/resources/templates/work/overTimeForm.html
src/main/resources/templates/work/workDetails.html
src/main/resources/templates/work/workSchedule.html

사이드바에 a태그 범위를 늘려서 li전체 어떤 부분을 눌러도 페이지 이동하게 수정, 캘린더 연차 출력 수정했고 연장근무테이블이랑 dto 자료형 수정했습니다

사이드바 경로 수정 및 DTO와 테이블 자료형 수정

---

src/main/java/com/example/projectdemo/domain/edsm/controller/EdsmController.java
src/main/java/com/example/projectdemo/domain/edsm/controller/EdsmDetailController.java
src/main/java/com/example/projectdemo/domain/edsm/controller/EdsmFormController.java
src/main/java/com/example/projectdemo/domain/edsm/dao/EdsmDAO.java
src/main/java/com/example/projectdemo/domain/edsm/services/EdsmService.java
src/main/resources/mappers/EdsmMapper.xml
src/main/resources/static/assets/css/edsm/edsmMain.css
src/main/resources/templates/edsm/edsmDetail/businessContactDetail.html
src/main/resources/templates/edsm/edsmDetail/cashDisbuVoucherDetail.html
src/main/resources/templates/edsm/edsmDetail/leavesDetail.html
src/main/resources/templates/edsm/edsmDetail/letterOfApprovalDetail.html
src/main/resources/templates/edsm/edsmDetail/overtimeDetail.html
src/main/resources/templates/edsm/edsmForm/businessContact.html
src/main/resources/templates/edsm/edsmForm/cashDisbuVoucher.html
src/main/resources/templates/edsm/edsmForm/letterOfApproval.html
src/main/resources/templates/edsm/edsmMyDocument/approvalDocument.html
src/main/resources/templates/edsm/edsmMyDocument/myWrittenDocument.html
src/main/resources/templates/edsm/edsmMyDocument/rejectedDocument.html
src/main/resources/templates/edsm/expected.html
src/main/resources/templates/edsm/input.html
src/main/resources/templates/edsm/main.html
src/main/resources/templates/edsm/wait.html

결재상태 실시간 갯수 표시기능 구현 
반응형으로 화면 작아졌을시 작성하기 버튼 생성 구현
정말 마지막 풀리...

결재상태 갯수 변경사항

---

src/main/java/com/example/projectdemo/domain/leave/controller/LeaveController.java
src/main/resources/templates/attend/attendLeavesHistory.html

휴가내역 페이지 휴가일수 수정

---

src/main/resources/static/assets/css/board/board-common.css
src/main/resources/static/assets/css/fragments/sub-sidebar-common.css
src/main/resources/static/assets/css/org/org.css
src/main/resources/templates/org/org.html

Style. 조직도 레이아웃 스타일 개선
Style. 게시판 레이아웃 스타일 개선
FIx. 조직도 페이지 모바일 환경에서 헤더가 화면을 벗어나는 문제 수정

Style. 조직도 및 게시판 레이아웃 개선, FIx. 모바일 환경에서의 헤더 위치 문제 수정

---

src/main/java/com/example/projectdemo/domain/attendance/scheduler/AutoCheckoutScheduler.java
src/main/java/com/example/projectdemo/domain/attendance/service/HolidayService.java
src/main/java/com/example/projectdemo/domain/leave/controller/LeaveController.java
src/main/java/com/example/projectdemo/domain/leave/scheduler/LeaveScheduler.java
src/main/java/com/example/projectdemo/domain/work/controller/WorkController.java
src/main/resources/static/assets/css/attend/attendAnnualStatistics.css
src/main/resources/static/assets/css/work/overTimeForm.css
src/main/resources/static/assets/css/work/workDetails.css
src/main/resources/static/assets/css/work/workSchedule.css
src/main/resources/templates/main.html
src/main/resources/templates/work/overTimeForm.html
src/main/resources/templates/work/workSchedule.html

디자인 및 연장근무신청서 수정

---

src/main/java/com/example/projectdemo/domain/board/controller/BoardController.java
src/main/java/com/example/projectdemo/domain/board/mapper/PostsMapper.java
src/main/java/com/example/projectdemo/domain/board/service/PostsService.java
src/main/java/com/example/projectdemo/main/MainPageFacadeImpl.java
src/main/resources/mappers/PostsMapper.xml
src/main/resources/static/assets/css/org/org.css
src/main/resources/templates/board/edit.html
src/main/resources/templates/board/write.html
src/main/resources/templates/main.html

Remove. 게시판 썸머노트 코드 삽입 기능 제거
Style. 조직도에 호버 시 커서 스타일 적용
Fix. 통합 게시판 목록에서 비활성화된 게시판의 게시글 필터링
Fix: 메인페이지 자유게시판 게시글 제한 쿼리 추가 (4개)

Remove 게시판 썸머노트 코드 삽입 기능 제거, Style 조직도 호버 시 커서 스타일 적용, Fix 비활성화된 게시판 게시글 필터링 및 메인페이지 자유게시판 게시글 4개 제한 쿼리 추가

---

src/main/resources/static/assets/css/fragments/sidebar-common.css
src/main/resources/static/assets/css/main-page.css
src/main/resources/static/assets/js/fragments/sidebar-common.js
src/main/resources/templates/booking/booking-main.html
src/main/resources/templates/fragments/sidebar-toggle.html
src/main/resources/templates/projects/task-register.html
src/main/resources/templates/projects/work-management.html

Feat: 모바일 환경에서 세부 사이드바 표시 기능 추가 (예약)
Feat: 모바일 환경에서 세부 사이드바 표시 기능 추가 (업무관리)
Style. 메인페이지 모바일 반응형
Fix. 사이드바 토글 버튼 - 브라우저 간 호환성 문제 해결 (파이어폭스에서 발생하던 오류 수정)

Feat & Fix: 모바일 사이드바 표시 기능 및 반응형 스타일 개선(예약, 업무관리), 사이드바 토글 호환성 문제 해결

---

src/main/resources/static/assets/css/contact/contact.css
src/main/resources/static/assets/css/mypage/mypage.css
src/main/resources/static/assets/js/contact/contact.js
src/main/resources/static/assets/js/mypage/mypage.js
src/main/resources/templates/contact/contact.html
src/main/resources/templates/mypage/mypage.html

- 주소록 페이지 반응형 레이아웃 개선
- 마이페이지 반응형 레이아웃 개선

주소록 및 마이페이지 반응형 레이아웃 개선

---

src/main/java/com/example/projectdemo/domain/leave/controller/LeaveController.java
src/main/java/com/example/projectdemo/domain/work/controller/WorkController.java

전체페이지 Sysout, console 제거

---

src/main/resources/templates/fragments/sidebar/work-sidebar.html

Style: 업무관리 사이드바에 반응형 숨김 클래스 d-none d-xxl-block 추가

Style: 업무관리 사이드바에 반응형 숨김 클래스 d-none d-xxl-block 추가

---

src/main/java/com/example/projectdemo/domain/booking/util/BookingTimeUtils.java
src/main/resources/mappers/PostsMapper.xml

자유게시판 및 회의실 예약 타일수정
